ci: jest 테스트 환경 수정

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -1,4 +1,4 @@
-name: Run Jest Tests
+name: Run Jest Tests For '02. 렌더링/02'
 
 on:
   pull_request:
@@ -16,10 +16,18 @@ jobs:
       - name: Use Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '14'
+          node-version: '20'
 
       - name: Install Dependencies
         run: npm ci
 
       - name: Run Jest Tests
-        run: npm test -- --coverage -- '02. 렌더링/02'
+        run: npm test -- --coverage  --ci --reporters=default --reporters=jest-junit -- '02. 렌더링/02'
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: JEST Tests # Name of the check run which will be created
+          path: junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
